--
-- Bonus...
--

-- DROP TABLE IF EXISTS series_viewers; -- a viewer's series
-- CREATE TABLE series_viewers (
--   -- id           serial       PRIMARY KEY, -- not using this in our join table...
--   viewer_id integer REFERENCES viewers(id) NOT NULL,
--   series_id integer REFERENCES series(id) NOT NULL
-- );

-- DROP TABLE IF EXISTS genres;
-- DROP TABLE IF EXISTS genres_series;
-- CREATE TABLE genres (
--   id   serial       PRIMARY KEY,
--   name varchar(127) NOT NULL
-- );
-- CREATE TABLE genres_series (
--   id        serial  PRIMARY KEY, -- not using this in our join table...
--   series_id integer NOT NULL,
--   genre_id  integer NOT NULL
-- );
--
-- DROP TABLE IF EXISTS flags;
-- DROP TABLE IF EXISTS flags_episodes;
-- CREATE TABLE flags (
--   id   serial       PRIMARY KEY,
--   name varchar(127) NOT NULL
-- );
-- CREATE TABLE flags_episodes (
--   id        serial  PRIMARY KEY, -- not using this in our join table...
--   episode_id integer NOT NULL,
--   series_id  integer NOT NULL
-- );
-- DROP TABLE IF EXISTS dvrs;
-- DROP TABLE IF EXISTS dvrs_viewers;
-- DROP TABLE IF EXISTS dvrs_recordings;

-- CREATE TABLE dvrs (
--   id              serial  PRIMARY KEY, -- not using this in our join table...
--   serial_number   integer NOT NULL,
--   hard_drive_size integer NOT NULL,
--   zip_code        varchar(5) NOT NULL
-- );

-- CREATE TABLE dvrs_viewers (
--   dvr_id    integer REFERENCES dvrs(id),
--   viewer_id integer REFERENCES viewers(id)
-- );

-- CREATE TABLE dvrs_recordings (
--   dvr_id        integer REFERENCES dvrs(id),
--   recordings_id integer REFERENCES recordings(id)
-- );
